--a
SELECT L.LID 
FROM LION L
WHERE SDO_FILTER (
	L.COORD,SDO_GEOMETRY(2003, NULL,NULL,SDO_ELEM_INFO_ARRAY(1,1003,1), 
	SDO_ORDINATE_ARRAY(150,200,400,350)),'QUERYTYPE=WINDOW'
	)='TRUE';


--b
SELECT L.LID 
FROM LION L, PONDS P
WHERE SDO_WITHIN_DISTANCE(
	L.COORD,P.POND,'DISTANCE=150'
	)='TRUE' AND P.PID='P1';

--d
SELECT P.PID ,SDO_NN_DISTANCE(1) DISTANCE
FROM LION L, PONDS P
WHERE L.LID ='L2' AND MDSYS.SDO_NN(P.POND,L.COORD,'SDO_NUM_RES=3',1)='TRUE'
ORDER BY DISTANCE ;

--f 
SELECT L.LID, P.PID
FROM TABLE (SDO_JOIN('LION','COORD','PONDS','POND','MASK=INSIDE+ ON')) C, LION L, PONDS P
WHERE C.ROWID1=L.ROWID AND C.ROWID2=P.ROWID;

--h
SELECT ID 
FROM REGIONS 
WHERE ID IN (
	SELECT R.ID 
	FROM REGIONS R, LION L
	WHERE SDO_ANYINTERACT(L.COORD, R.POLYGON)='TRUE'
	) 
AND ID NOT IN(
	SELECT R.ID FROM REGIONS R, PONDS P
	WHERE SDO_ANYINTERACT(P.POND, R.POLYGON
	)='TRUE'
);

--i
SELECT LID 
FROM LION 
WHERE LID NOT IN(
	SELECT L.LID FROM AMBULANCE A, LION L
	WHERE SDO_ANYINTERACT(L.COORD,A.AREA)='TRUE');



